# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Spenderr' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Spenderr
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

  target 'SpenderrTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SpenderrUITests' do
    # Pods for testing
  end

end
